stages:
  - build
  - test
  - deploy

image: alpine

build_b:
  stage: build
  script:
    - echo "This job builds something else."

test_b:
  stage: test
  needs: build_b
  script:
    - echo "This job tests something else."

deploy_b:
  stage: deploy
  needs: test_b
  script:
    - echo "This job deploys something else."